### ISSUE TITLE
Chapter Logos

### ISSUE THREAD

**Issue by VinayGupta23** [IEEECS-VIT/gravitas-windows#1]
Just for convenience, the specifications are listed here:
- Square Logo - 360 x 360 px
- Wide Logo - 720 x 360 px
- Transparent Background
- Pad the actual logo on all sides uniformly, see attached picture for details.
- Prefer square logo, wide logo is only a last resort.

Create the images in `.png` format. Also, please ensure that all logos put together must not exceed a few (2-3) MB in size.
After syncing the branches, save the logos in the `GravitasApp\Assets\ChapterLogos` folder under the `dataTest` branch.

Reference:
![specifications](https://cloud.githubusercontent.com/assets/8874825/8397659/c45e7e28-1df0-11e5-8564-5a06e4d7aac1.png)

**Comment by VinayGupta23** [comment]
@amolgautam25 @sukriti27  - Guys this is for you.

And the `.psd` files should be available in the drive link.

**Comment by VinayGupta23** [comment]
@sukriti27  what's the status?

One thing I forgot, in some logos if its coming slightly into the padding region, its okay as long as its few pixels.

**Comment by VinayGupta23** [comment]
For the time being, I think we could edit these logos further (please just manage, I know most of the `psd`s given to us are very bad):

Add a white background and slightly enlarge it.
![cclogo](https://cloud.githubusercontent.com/assets/8874825/8508056/4a7689b0-227e-11e5-9799-10aa68a7696c.png)

This logo is looking compressed, change it to a wide tile.
![ieee embs logo](https://cloud.githubusercontent.com/assets/8874825/8508059/73b18744-227e-11e5-878a-7d2419ed3816.png)

The bottom few words seem cut off, can you edit again? (Also try a wide tile if resolution is good).
![iet](https://cloud.githubusercontent.com/assets/8874825/8508063/828cb32e-227e-11e5-883f-e0a559449fb9.png)

If possible we can add a suitably coloured background, since its difficult to see the text on white.
![vit spartans logo - copy](https://cloud.githubusercontent.com/assets/8874825/8508065/9ffb332c-227e-11e5-8d4b-9c4aa987312d.png)

**Comment by VinayGupta23** [comment]
@sukriti27 Please acknowledge when you receive this.

**Comment by sukriti27** [comment]
Okay. Will make the changes.

**Comment by sukriti27** [comment]
PFA

I did the changes.

**Comment by VinayGupta23** [comment]
Hey, the files aren't there. Attaching photos in mail and replying to github doesn't work if you tried that...
Post them here directly.

**Comment by VinayGupta23** [comment]
@sukriti27,
Last question, is there no better logo quality available for this one?
And was there any background or it wasn't there?
![ieeepcs](https://cloud.githubusercontent.com/assets/8874825/8731637/53277348-2c16-11e5-85c8-150f46668d48.png)

**Comment by sukriti27** [comment]
I will search for a better quality logo. There wasn't any background.

**Comment by VinayGupta23** [comment]
Sure.

**Comment by VinayGupta23** [comment]
@sukriti27  Any luck finding a better logo?

**Comment by sukriti27** [comment]
Couldn't find a good quality logo with transparent background. I.I got one
with some background from their Facebook page. Should I add it to the
folder?

**Comment by VinayGupta23** [comment]
Can you first post that image here so we can decide?

**Comment by VinayGupta23** [comment]
@sukriti27 
So, these are the file names required. Also, make sure every chapter has a logo in the folder as listed below.
Stick to only the square 360x360 setting (as above), and find suitable logos to fit the square or trim.

``` json
{
    "ACM": "acm",
    "AICHE": "aiche",
    "ASCE": "asce",
    "ASME": "asme",
    "AYUDA": "ayuda",
    "Code Chef": "codechef",
    "Creativity Club": "creativityclub",
    "CSI": "csi",
    "E CELL": "ecell",
    "Hindu E-Plus": "hindue-plus",
    "Huawei Club VIT": "huaweiclubvit",
    "IEEE": "ieee",
    "IEEE CS": "ieeecs",
    "IEEE EMBS": "ieeeembs",
    "IEEE MTT-S": "ieeemtt-s",
    "IEEE PCS": "ieeepcs",
    "IEEE WIE": "ieeewie",
    "IEEE-NPSS": "ieee-npss",
    "IEEE-PES": "ieee-pes",
    "IEEE-RAS": "ieee-ras",
    "IEI": "iei",
    "IET": "iet",
    "IETE": "iete",
    "IETE-ISF": "iete-isf",
    "IIChe": "iiche",
    "Individual": "individual",
    "iOS DEVELOPERS": "iosdevelopers",
    "ISA": "isa",
    "ISOI": "isoi",
    "ISTE": "iste",
    "Nature Club": "natureclub",
    "RoboVITics": "robovitics",
    "SABEST": "sabest",
    "SAE": "sae",
    "SEDS": "seds",
    "SMCE": "smce",
    "SME": "sme",
    "TAG": "tag",
    "TEC": "tec",
    "The Debate Society": "thedebatesociety",
    "Trekking CLub": "trekkingclub",
    "VIT Animation Club": "vitanimationclub",
    "VIT Quiz Club": "vitquizclub",
    "VIT Spartans": "vitspartans",
    "YRC": "yrc"
}
```

And do find out what AICHE and IICHE are, and if they are errors or they actually exist.

**Comment by VinayGupta23** [comment]
Even a simple logo will do, and a white background is sufficient. Don't bother with transparency unless background is coloured.
